name: Build and deploy .NET application to container app childgrowth-app-202502280100
on:
  push:
    branches:
    - main
env:
  CONTAINER_APP_CONTAINER_NAME: child-growth
  CONTAINER_APP_NAME: childgrowth-app-202502280100
  CONTAINER_APP_RESOURCE_GROUP_NAME: ChildGrowth
  CONTAINER_REGISTRY_LOGIN_SERVER: childgrowth20250228010857.azurecr.io
  DOCKER_FILE_PATH: ControllerLayer/Dockerfile
  PROJECT_NAME_FOR_DOCKER: controllerlayer
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.ChildGrowth20250228010857_USERNAME_B71D }}
        password: ${{ secrets.ChildGrowth20250228010857_PASSWORD_B71D }}
    - name: Build and push container image to registry
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
        file: ${{ env.DOCKER_FILE_PATH }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.childgrowth_app_202502280100_SPN }}
    - name: Deploy to containerapp
      uses: azure/CLI@v2
      with:
        inlineScript: >
          az config set extension.use_dynamic_install=yes_without_prompt

          az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} --username ${{ secrets.ChildGrowth20250228010857_USERNAME_B71D }} --password ${{ secrets.ChildGrowth20250228010857_PASSWORD_B71D }}

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
    - name: logout
      run: >
        az logout
